import React,{useState,useEffect} from 'react';
import {Head,Link,router} from '@inertiajs/react';
import {LayoutDashboard,Users,ReceiptText,Wallet,Landmark,UserRound,CalendarCheck,BriefcaseBusiness,Repeat2,Truck,ChartNoAxesCombined,BookOpen,Settings,Search,Bell,ChevronDown,ChevronRight,Plus,ArrowUpRight,ArrowRight,Download,Printer,Menu,X,LogOut,Layers,Check} from 'lucide-react';
import Dashboard from '../Components/Dashboard';
import TransactionForm from '../Components/TransactionForm';
import {ModulePage} from '../Components/Modules';
import RecordDetail from '../Components/RecordDetail';
import {Reports,Ledgers,SettingsPage} from '../Components/Reports';
import {Avatar,dateLabel,code} from '../Components/UI';
const navigation=[{label:'WORKSPACE',items:[['dashboard','Overview',LayoutDashboard],['customers','Customers',Users],['invoices','Invoices',ReceiptText],['receipts','Receive money',Wallet],['cashbook','Cash & bank',Landmark]]},{label:'PEOPLE & OPERATIONS',items:[['employees','Employees',UserRound],['attendance','Attendance',CalendarCheck],['payrolls','Payroll',BriefcaseBusiness],['expenses','Expenses',ReceiptText],['fixed-expenses','Fixed expenses',Repeat2],['gate-passes','Gate passes',Truck]]},{label:'BUSINESS INSIGHTS',items:[['reports','Reports',ChartNoAxesCombined],['ledgers','Ledgers',BookOpen]]}];
export const pageTitles={dashboard:'Overview',customers:'Customers',invoices:'Invoices',receipts:'Receive money',cashbook:'Cash & bank',employees:'Employees',attendance:'Attendance',payrolls:'Payroll',expenses:'Expenses','fixed-expenses':'Fixed expenses','gate-passes':'Gate passes',reports:'Reports',ledgers:'Customer & invoice ledgers',settings:'Workspace settings'};
const subtitles={customers:'Good relationships start with the details.',invoices:'Every order, every invoice, effortlessly connected.',receipts:'Turn outstanding invoices into settled accounts.',cashbook:'A clear view of every dollar coming in and going out.',employees:'The people who keep your business moving.',attendance:'Every day counts. Keep your team in sync.',payrolls:'From attendance to payday, all in one place.',expenses:'Small details. A clearer picture of your costs.','fixed-expenses':'Stay one step ahead of your recurring commitments.','gate-passes':'Track every movement, from your floor to their door.',reports:'Your business, with a little more perspective.',ledgers:'Follow the story behind every balance.',settings:'Make this workspace yours.'};
const actionTitles={customers:'Add customer',invoices:'Create invoice',receipts:'Receive money',cashbook:'Add account',employees:'Add employee',attendance:'Mark attendance',payrolls:'Generate payroll',expenses:'Add expense','fixed-expenses':'New fixed expense','gate-passes':'Create gate pass'};
export default function Workspace({page,recordId,data,today,auth,flash,demo}) {
 const [modal,setModal]=useState(null),[sidebar,setSidebar]=useState(false),[globalSearch,setGlobalSearch]=useState(''),[notice,setNotice]=useState(false),[profile,setProfile]=useState(false),[range,setRange]=useState('30');
 const [toast,setToast]=useState('');
 useEffect(()=>{if(flash.success){setToast(flash.success);const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)}},[flash]);
 useEffect(()=>{setSidebar(false);setGlobalSearch('');setNotice(false);setProfile(false)},[page,recordId]);
 const open=(action,initial={})=>setModal({action,initial}); const admin=auth.user.role==='admin';
 const globalResults=globalSearch.trim()?['customers','invoices','receipts','employees','gate_passes'].flatMap(table=>data[table].map(r=>({type:table.replace('_','-'),id:r.id,label:r.name||code(table.replace('_','-'),r.id),extra:r.phone||r.date}))).filter(r=>`${r.label} ${r.extra}`.toLowerCase().includes(globalSearch.toLowerCase())).slice(0,8):[];
 return <div className="app-shell"><Head title={pageTitles[page]}/>{sidebar&&<div className="sidebar-overlay" onClick={()=>setSidebar(false)}/>}
 <aside className={`sidebar ${sidebar?'is-open':''}`}><Link href="/" className="brand"><span className="brand-symbol"><Layers size={23}/></span><span>threadline<span className="brand-dot">.</span><small>TEXTILE WORKSPACE</small></span></Link><button className="workspace-switch" onClick={()=>router.visit('/settings')}><span className="workspace-avatar">T</span><span><strong>My textile business</strong><small>{demo?'Demo workspace':'Business workspace'}</small></span><ChevronDown size={14}/></button><nav>{navigation.map(group=><div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(([key,label,Icon])=><Link key={key} href={key==='dashboard'?'/':'/'+key} className={`nav-item ${page===key?'active':''}`}><Icon size={18}/><span>{label}</span>{key==='invoices'&&<span className="nav-count">{data.invoices.filter(i=>i.due>0).length}</span>}{key===page&&<span className="nav-active-dot"/>}</Link>)}</div>)}</nav><div className="sidebar-bottom"><div className="sidebar-tip"><span className="tip-icon"><Layers size={20}/></span><strong>A little more clarity.</strong><p>All your business essentials.<br/>One connected workspace.</p><Link href="/reports">Explore reports <ArrowUpRight size={15}/></Link></div><Link className={`nav-item ${page==='settings'?'active':''}`} href="/settings"><Settings size={18}/><span>Settings</span></Link><div className="sidebar-user"><Avatar name={auth.user.name}/><span><strong>{auth.user.name}</strong><small>{admin?'Workspace administrator':'Team member'}</small></span><button className="icon-button" aria-label="Sign out" onClick={()=>router.post('/logout')}><LogOut size={16}/></button></div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={()=>setSidebar(true)}><Menu size={21}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{pageTitles[page]}</strong></div><div className="topbar-right"><div className="global-search"><Search size={16}/><input aria-label="Search workspace" value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} placeholder="Search anything…"/><kbd>⌕</kbd>{globalSearch&&<div className="search-results">{globalResults.length?globalResults.map(r=><Link key={r.type+r.id} href={`/${r.type}/${r.id}`}><Search size={14}/><span>{r.label}<small>{r.type} · {r.extra}</small></span><ArrowUpRight size={15}/></Link>):<p>No matching records found.</p>}</div>}</div><div className="topbar-divider"/><div className="popover-wrap"><button className="icon-button notification-button" aria-label="View notifications" onClick={()=>setNotice(!notice)}><Bell size={19}/><i/></button>{notice&&<div className="popover"><h3>On your radar</h3><p>{data.invoices.filter(i=>i.due>0&&i.due_date<today).length} overdue invoices need attention.</p><Link href="/invoices?status=Unpaid">Review invoices <ArrowRight size={14}/></Link><p>{data.fixed_expenses.filter(f=>f.active&&f.next_due<=today).length} recurring payments are due.</p><Link href="/fixed-expenses">View upcoming payments <ArrowRight size={14}/></Link></div>}</div><div className="popover-wrap"><button className="topbar-profile" onClick={()=>setProfile(!profile)}><Avatar name={auth.user.name}/><span><strong>{auth.user.name}</strong><small>{admin?'Administrator':'Team member'}</small></span><ChevronDown size={14}/></button>{profile&&<div className="popover profile-popover"><Link href="/settings">Profile & security</Link><button className="text-button" onClick={()=>router.post('/logout')}>Sign out <LogOut size={15}/></button></div>}</div></div></header>
<main className="main-content">{page==='dashboard'?<Dashboard data={data} today={today} user={auth.user} open={open} range={range} setRange={setRange}/>:recordId?<RecordDetail key={page+recordId} {...{page,recordId,data,today,open,admin}}/>:<><div className="page-heading"><div><div className="eyebrow">THREADLINE WORKSPACE</div><h1>{pageTitles[page]}</h1><p>{subtitles[page]}</p></div><div className="heading-actions">{page!=='settings'&&<button className="button secondary" onClick={()=>window.print()}><Printer size={16}/>Print</button>}{actionTitles[page]&&(!['payrolls','cashbook'].includes(page)||admin)&&<button className="button primary" onClick={()=>open(page==='cashbook'?'accounts':page)}><Plus size={17}/>{actionTitles[page]}</button>}</div></div>{page==='settings'?<SettingsPage user={auth.user} data={data} demo={demo}/>:page==='reports'?<Reports data={data} today={today}/>:page==='ledgers'?<Ledgers data={data}/>:<ModulePage key={page} {...{page,data,today,open,admin}}/>}</>}
 <footer className="app-footer"><span>© {today.slice(0,4)} Threadline. Every detail, connected.</span><span><i/>{demo?'Demo workspace · USD':'Workspace · USD'}<span className="footer-separator">/</span>{dateLabel(today)}</span></footer></main></div>
 {modal&&<TransactionForm key={modal.action} action={modal.action} initial={modal.initial} data={data} today={today} onClose={()=>setModal(null)}/>} {toast&&<div className="toast" role="status"><span><Check size={17}/></span>{toast}<button className="icon-button" onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={15}/></button></div>}</div>;
}
