import React from 'react';
import {Link} from '@inertiajs/react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {ArrowUpRight,ArrowRight,Plus,ReceiptText,Users,Wallet,TrendingUp,ChevronRight,CalendarDays,ArrowDownLeft,ArrowUpLeft,Package,MoveUpRight} from 'lucide-react';
import {Card,Stat,Table,Ref,Badge,Avatar,money,shortMoney,sum,code,dateLabel} from './UI';
export default function Dashboard({data,today,user,open,range,setRange}) {
 const start=new Date(today+'T12:00:00');start.setDate(start.getDate()-Number(range)+1);const from=start.toISOString().slice(0,10);
 const invoices=data.invoices.filter(i=>i.status==='Posted'&&i.date>=from&&i.date<=today);
 const receipts=data.receipts.filter(r=>r.date>=from&&r.date<=today);
 const expenses=data.expenses.filter(e=>e.date>=from&&e.date<=today);
 const revenue=sum(invoices,'total');const collected=sum(receipts,'amount');const outstanding=sum(data.customers,'balance');
 const rate=revenue?Math.round(sum(invoices,'paid')/revenue*100):0;
 const trend=Array.from({length:Number(range)},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const date=d.toISOString().slice(0,10);return {date,label:d.toLocaleDateString('en-US',{month:'short',day:'numeric'}),revenue:sum(invoices.filter(r=>r.date===date),'total')/100,collections:sum(receipts.filter(r=>r.date===date),'amount')/100}});
 const categories=Object.entries(expenses.reduce((a,e)=>{a[e.category]=(a[e.category]||0)+Number(e.amount);return a},{})).sort((a,b)=>b[1]-a[1]);
 const expenseTotal=sum(expenses,'amount');
 const colors=['#7860df','#a695ec','#c5baf4','#e5defa','#f0ecfc'];let offset=0;
 const segments=categories.map(([name,value],i)=>{const start=offset;offset+=value/expenseTotal*100;return `${colors[Math.min(i,4)]} ${start}% ${offset}%`}).join(',');
 const invoiceColumns=[{key:'customer',label:'Customer',render:r=>{const c=data.customers.find(c=>c.id===r.customer_id);return <div className="person-cell"><Avatar name={c?.name}/><div><Ref type="customers" id={c?.id}>{c?.name}</Ref><small>{code('customers',c?.id)}</small></div></div>}},{key:'id',label:'Invoice',render:r=><Ref type="invoices" id={r.id}/>},{key:'date',label:'Date',render:r=>dateLabel(r.date)},{key:'payment_status',label:'Status',render:r=><Badge>{r.payment_status}</Badge>},{key:'total',label:'Amount',right:true,render:r=><strong>{money(r.total)}</strong>}];
 return <><div className="page-heading dashboard-heading"><div><div className="eyebrow">YOUR BUSINESS, AT A GLANCE</div><h1>Welcome back, {user.name.split(' ')[0]} <span className="wave">\u2733</span></h1><p>Here\u2019s what\u2019s happening at your textile business today.</p></div><div className="heading-actions"><div className="select-button"><CalendarDays size={15}/><select aria-label="Dashboard date range" value={range} onChange={e=>setRange(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></div><button className="button primary" onClick={()=>open('invoices')}><Plus size={17}/>Create invoice</button></div></div>
 <div className="stats-grid"><Stat label="Total revenue" value={money(revenue)} icon={ReceiptText} note={`${invoices.length} invoices this period`} accent/><Stat label="Money received" value={money(collected)} icon={Wallet} note={`${receipts.length} payments collected`}/><Stat label="Outstanding balance" value={money(outstanding)} icon={TrendingUp} note={`${data.invoices.filter(i=>i.due>0).length} invoices awaiting payment`}/><Stat label="Active customers" value={data.customers.filter(c=>c.status==='Active').length.toString().padStart(2,'0')} icon={Users} note="Growing together, thread by thread"/></div>
 <div className="dashboard-grid"><div className="dashboard-main"><div className="chart-grid"><Card title="Revenue overview" subtitle="A little perspective on your performance." action={<Link className="icon-button" aria-label="View revenue report" href="/reports"><ArrowUpRight size={18}/></Link>} className="revenue-card"><div className="chart-summary"><strong>{money(revenue)}</strong><span className="pill">Last {range} days</span></div><div className="chart-legend"><span><i/>Revenue</span><span><i className="pale"/>Collections</span></div><div className="revenue-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:12,right:5,bottom:0,left:-25}}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#947aeb" stopOpacity={.3}/><stop offset="100%" stopColor="#947aeb" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#efedf3" strokeDasharray="3 4"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#929098'}} minTickGap={35}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#929098'}} tickFormatter={n=>'$'+(n>=1000?n/1000+'k':n)}/><Tooltip formatter={n=>money(n*100)} contentStyle={{border:'1px solid #eeeaf5',borderRadius:12,fontSize:12}}/><Area type="monotone" dataKey="collections" stroke="#c5b8ee" fill="none" strokeWidth={2} strokeDasharray="4 4"/><Area type="monotone" dataKey="revenue" stroke="#8265dd" fill="url(#revenueFill)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></Card>
 <Card title="Expense breakdown" subtitle="Where your money goes." action={<Link href="/expenses" aria-label="View expenses" className="icon-button"><ArrowUpRight size={18}/></Link>}><div className="donut" style={{background:segments?`conic-gradient(${segments})`:'#eeeaf8'}}><div><span>Total expenses</span><strong>{shortMoney(expenseTotal)}</strong></div></div><div className="donut-legend">{categories.slice(0,4).map(([name,value],i)=><Link href={'/expenses?category='+encodeURIComponent(name)} key={name}><i style={{background:colors[i]}}/><span>{name}</span><strong>{Math.round(value/expenseTotal*100)}%</strong></Link>)}{!categories.length&&<span>No expenses in this period</span>}</div></Card></div>
 <Card title="Recent invoices" subtitle="Your latest orders, all in one place." className="recent-card" action={<Link href="/invoices" className="text-button">View all <ArrowRight size={14}/></Link>}><Table rows={data.invoices.slice(0,5)} columns={invoiceColumns} searchable={false} pageSize={5}/></Card>
 <div className="bottom-grid"><Card title="Recent activity" action={<Link href="/settings" className="text-button">View activity <ArrowUpRight size={14}/></Link>}><div className="activity-list">{data.transactions.slice(0,3).map(t=><div className="activity-item" key={t.id}><span className="activity-icon">{t.type==='in'?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><div><Ref type={t.source_type==='transactions'?'cashbook':t.source_type} id={t.source_type==='transactions'?t.account_id:t.source_id}>{t.description}</Ref><small>{dateLabel(t.date)} \u00b7 {data.accounts.find(a=>a.id===t.account_id)?.name}</small></div><strong>{t.type==='in'?'+':'\u2212'}{money(t.amount)}</strong></div>)}</div></Card><div className="insight-card"><span className="insight-mark"><LayersIcon/></span><span className="eyebrow">EVERY DETAIL, CONNECTED</span><h3>Less paperwork.<br/>More possibility.</h3><p>From the first invoice to the final payment. Your whole business, in sync.</p><Link href="/reports">Explore your reports <ArrowUpRight size={17}/></Link></div></div>
 </div><aside className="dashboard-side"><Card title="Collection progress" action={<span className="mini-dots">\u22ef</span>}><div className="progress-ring" style={{'--progress':`${Math.min(rate,100)*3.6}deg`}}><div><strong>{rate}%</strong><span>collected</span></div></div><div className="progress-caption"><strong>Keep the momentum going</strong><p>{money(sum(invoices,'paid'))} of {money(revenue)} collected</p></div><Link href="/receipts" className="button secondary full">Receive money <ArrowUpRight size={15}/></Link></Card>
 <Card title="Upcoming payments" subtitle="A heads-up for what\u2019s next." action={<CalendarDays size={16}/>}><div className="upcoming-list">{data.fixed_expenses.filter(f=>f.active).sort((a,b)=>a.next_due.localeCompare(b.next_due)).slice(0,3).map(f=><Link href={'/fixed-expenses/'+f.id} className="upcoming-item" key={f.id}><span className="date-tile"><small>{new Date(f.next_due+'T12:00:00').toLocaleDateString('en-US',{month:'short'})}</small><strong>{f.next_due.slice(8)}</strong></span><span><strong>{f.name}</strong><small>{money(f.amount)}</small></span><ChevronRight size={15}/></Link>)}</div><Link href="/fixed-expenses" className="text-button upcoming-all">View all payments <ArrowRight size={14}/></Link></Card>
 <Card title="Quick actions"><div className="quick-grid">{[{action:'customers',icon:Users,label:'Add customer'},{action:'receipts',icon:Wallet,label:'Receive money'},{action:'expenses',icon:ReceiptText,label:'Add expense'},{action:'gate-passes',icon:Package,label:'Gate pass'}].map(a=><button key={a.action} onClick={()=>open(a.action)}><span><a.icon size={20}/></span>{a.label}</button>)}</div></Card>
 <div className="workspace-health"><span className="health-dot"/><div><strong>Everything is connected</strong><span>One workspace. One source of truth.</span></div></div></aside></div>
 </>;
}
function LayersIcon(){return <svg viewBox="0 0 64 64" fill="none"><path d="M8 24L32 10L56 24L32 38Z" stroke="currentColor" strokeWidth="2"/><path d="M8 34L32 48L56 34M8 44L32 58L56 44" stroke="currentColor" strokeWidth="2"/></svg>}
