import React,{useState} from 'react';
import {Link} from '@inertiajs/react';
import {ArrowUpRight,ArrowRight,Plus,Landmark,Wallet,Layers,Info,FileText,SlidersHorizontal,Download,Pencil,Trash2,BriefcaseBusiness,CalendarCheck} from 'lucide-react';
import {Stat,Table,Ref,Badge,Avatar,money,dateLabel,code,sum,exportCSV} from './UI';
export const cashColumns=data=>[{key:'date',label:'Date',render:r=>dateLabel(r.date)},{key:'description',label:'Description',render:r=><div><strong>{r.description}</strong><small>{r.source_type.replaceAll('_',' ')}</small></div>},{key:'source',label:'Source',render:r=>r.source_type==='transactions'?<span>{code('transactions',r.id)}</span>:<Ref type={r.source_type} id={r.source_id}/>},{key:'account_id',label:'Account',render:r=><Ref type="cashbook" id={r.account_id}>{data.accounts.find(a=>a.id===r.account_id)?.name}</Ref>},{key:'in',label:'Money in',right:true,render:r=>r.type==='in'?money(r.amount):'—'},{key:'out',label:'Money out',right:true,render:r=>r.type==='out'?money(r.amount):'—'},{key:'balance',label:'Account balance',right:true,render:r=><strong>{money(r.balance)}</strong>}];
export function runningTransactions(data){const balances=Object.fromEntries(data.accounts.map(a=>[a.id,Number(a.opening_balance)]));return [...data.transactions].sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id).map(t=>{balances[t.account_id]+=(t.type==='in'?1:-1)*Number(t.amount);return {...t,balance:balances[t.account_id]}}).reverse()}
export function useColumns(data,open,admin,today){
 const customer=id=>data.customers.find(c=>c.id===id);const employee=id=>data.employees.find(e=>e.id===id);
 const customerCol={key:'customer_name',label:'Customer',render:r=><Ref type="customers" id={r.customer_id}>{customer(r.customer_id)?.name}</Ref>};
 const employeeCol={key:'employee_name',label:'Employee',render:r=><div className="person-cell"><Avatar name={employee(r.employee_id)?.name}/><Ref type="employees" id={r.employee_id}>{employee(r.employee_id)?.name}</Ref></div>};
 const accountCol={key:'account_id',label:'Account',render:r=><Ref type="cashbook" id={r.account_id}>{data.accounts.find(a=>a.id===r.account_id)?.name}</Ref>};
 const date={key:'date',label:'Date',render:r=>dateLabel(r.date)};
 return {
 customers:[{key:'name',label:'Customer',render:r=><div className="person-cell"><Avatar name={r.name}/><div><Ref type="customers" id={r.id}>{r.name}</Ref><small>{code('customers',r.id)}</small></div></div>},{key:'phone',label:'Phone'},{key:'last_invoice',label:'Last invoice',render:r=>dateLabel(r.last_invoice)},{key:'last_payment',label:'Last payment',render:r=>dateLabel(r.last_payment)},{key:'status',label:'Status',render:r=><Badge>{r.status}</Badge>},{key:'balance',label:'Outstanding',right:true,render:r=><strong>{money(r.balance)}</strong>},{key:'actions',label:'Actions',render:r=>admin?<div className="row-actions"><button className="icon-button" onClick={()=>open('update-customer',{...r,opening_balance:r.opening_balance/100})} aria-label={'Edit '+r.name} title="Edit customer"><Pencil size={15}/></button><button className="icon-button danger" onClick={()=>open('delete-customer',{id:r.id,name:r.name,has_history:data.invoices.some(i=>i.customer_id===r.id)||data.receipts.some(receipt=>receipt.customer_id===r.id)})} aria-label={'Delete '+r.name} title="Delete customer"><Trash2 size={15}/></button></div>:<span>—</span>}],
 invoices:[{key:'id',label:'Invoice',render:r=><Ref type="invoices" id={r.id}/>},customerCol,date,{key:'due_date',label:'Due date',render:r=>dateLabel(r.due_date)},{key:'total',label:'Total',right:true,render:r=>money(r.total)},{key:'paid',label:'Paid',right:true,render:r=><Ref type="invoices" id={r.id}>{money(r.paid)}</Ref>},{key:'due',label:'Due',right:true,render:r=><strong>{money(r.due)}</strong>},{key:'payment_status',label:'Status',render:r=><Badge>{r.payment_status}</Badge>}],
 receipts:[{key:'id',label:'Receipt',render:r=><Ref type="receipts" id={r.id}/>},customerCol,date,accountCol,{key:'method',label:'Method'},{key:'amount',label:'Amount received',right:true,render:r=><strong>{money(r.amount)}</strong>},{key:'credit',label:'Unallocated credit',right:true,render:r=>money(r.credit)}],
 employees:[{key:'name',label:'Employee',render:r=><div className="person-cell"><Avatar name={r.name}/><div><Ref type="employees" id={r.id}>{r.name}</Ref><small>{code('employees',r.id)}</small></div></div>},{key:'department',label:'Department'},{key:'designation',label:'Designation'},{key:'joining_date',label:'Joined',render:r=>dateLabel(r.joining_date)},{key:'salary',label:'Base salary',render:r=><>{money(r.salary)}<small>{r.salary_type}</small></>},{key:'status',label:'Status',render:r=><Badge>{r.status}</Badge>},{key:'actions',label:'Actions',render:r=>admin?<div className="row-actions"><button className="icon-button" onClick={()=>data.attendance.some(a=>a.employee_id===r.id&&a.date.slice(0,7)===today.slice(0,7))?open('payrolls',{employee_id:r.id,period:today.slice(0,7)}):open('attendance',{employee_ids:[r.id],date:today})} aria-label={(data.attendance.some(a=>a.employee_id===r.id&&a.date.slice(0,7)===today.slice(0,7))?'Generate payroll for ':'Mark attendance for ')+r.name} title={data.attendance.some(a=>a.employee_id===r.id&&a.date.slice(0,7)===today.slice(0,7))?'Generate payroll':'Mark attendance first'}>{data.attendance.some(a=>a.employee_id===r.id&&a.date.slice(0,7)===today.slice(0,7))?<BriefcaseBusiness size={15}/>:<CalendarCheck size={15}/>}</button><button className="icon-button" onClick={()=>open('update-employee',{...r,salary:r.salary/100})} aria-label={'Edit '+r.name} title="Edit employee"><Pencil size={15}/></button><button className="icon-button danger" onClick={()=>open('delete-employee',{id:r.id,name:r.name,has_history:data.attendance.some(a=>a.employee_id===r.id)||data.payrolls.some(p=>p.employee_id===r.id)})} aria-label={'Delete '+r.name} title="Delete employee"><Trash2 size={15}/></button></div>:<span>—</span>}],
 attendance:[employeeCol,date,{key:'status',label:'Status',render:r=><Badge>{r.status}</Badge>},{key:'check_in',label:'Check-in'},{key:'check_out',label:'Check-out'},{key:'overtime',label:'Overtime',render:r=>r.overtime+' h'},{key:'payroll',label:'Payroll',render:r=>admin?<button className="text-button" onClick={()=>open('payrolls',{employee_id:r.employee_id,period:r.date.slice(0,7)})}>View / generate <ArrowUpRight size={14}/></button>:<Link href="/payrolls">View payroll</Link>}],
 payrolls:[{key:'id',label:'Payroll',render:r=><Ref type="payrolls" id={r.id}/>},employeeCol,{key:'period',label:'Period'},{key:'earned',label:'Earned',right:true,render:r=>money(r.earned)},{key:'net',label:'Net pay',right:true,render:r=><strong>{money(r.net)}</strong>},{key:'paid',label:'Paid',right:true,render:r=>money(r.paid)},{key:'status',label:'Status',render:r=><Badge>{r.paid>=r.net?'Paid':r.paid>0?'Partially Paid':'Unpaid'}</Badge>},{key:'action',label:'',render:r=>admin&&r.paid<r.net&&<button className="text-button" onClick={()=>open('pay-salary',{payroll_id:r.id,amount:(r.net-r.paid)/100})}>Pay salary <ArrowUpRight size={14}/></button>}],
 expenses:[{key:'id',label:'Voucher',render:r=><Ref type="expenses" id={r.id}/>},date,{key:'description',label:'Description',render:r=><div><strong>{r.description}</strong><small>{r.fixed_expense_id?'Recurring expense':'Variable expense'}</small></div>},{key:'category',label:'Category'},accountCol,{key:'amount',label:'Amount',right:true,render:r=><strong>{money(r.amount)}</strong>}],
 'fixed-expenses':[{key:'name',label:'Recurring expense',render:r=><Ref type="fixed-expenses" id={r.id}>{r.name}</Ref>},{key:'category',label:'Category'},{key:'frequency',label:'Frequency'},{key:'next_due',label:'Next due',render:r=>dateLabel(r.next_due)},{key:'amount',label:'Expected amount',right:true,render:r=><strong>{money(r.amount)}</strong>},{key:'active',label:'Status',render:r=><Badge>{r.active?'Active':'Inactive'}</Badge>},{key:'action',label:'',render:r=>r.active?<button className="text-button" onClick={()=>open('pay-fixed',{fixed_expense_id:r.id,expected_due:r.next_due,account_id:r.account_id,amount:r.amount/100})}>Mark paid <ArrowUpRight size={14}/></button>:null}],
 'gate-passes':[{key:'name',label:'Gate pass',render:r=><Ref type="gate-passes" id={r.id}>{r.name}</Ref>},date,{key:'type',label:'Movement',render:r=><Badge>{r.type}</Badge>},customerCol,{key:'invoice_id',label:'Invoice',render:r=><Ref type="invoices" id={r.invoice_id}/>},{key:'vehicle',label:'Vehicle'},{key:'quantity',label:'Quantity',render:r=>r.quantity+' '+r.unit},{key:'actions',label:'Actions',render:r=>admin?<div className="row-actions"><button className="icon-button" onClick={()=>open('update-gate-pass',{...r})} aria-label={'Edit '+r.name} title="Edit gate pass"><Pencil size={15}/></button><button className="icon-button danger" onClick={()=>open('delete-gate-pass',{id:r.id,name:r.name})} aria-label={'Delete '+r.name} title="Delete gate pass"><Trash2 size={15}/></button></div>:<span>—</span>}],cashbook:cashColumns(data),
 };
}
export function ModulePage({page,data,today,open,admin}){
 const params=new URLSearchParams(window.location.search);
 const [status,setStatus]=useState(params.get('status')||'all'),[account,setAccount]=useState('all'),[category,setCategory]=useState(params.get('category')||'all'),[month,setMonth]=useState(today.slice(0,7)),[from,setFrom]=useState(''),[to,setTo]=useState(''),[direction,setDirection]=useState('all');
 const columns=useColumns(data,open,admin,today);const table=page.replaceAll('-','_');let rows=page==='cashbook'?runningTransactions(data):data[table]||[];
 rows=rows.map(r=>({...r,customer_name:data.customers.find(c=>c.id===r.customer_id)?.name,employee_name:data.employees.find(e=>e.id===r.employee_id)?.name,record_code:code(page,r.id)}));
 if(status!=='all')rows=rows.filter(r=>(r.payment_status||r.status)===status);
 if(account!=='all')rows=rows.filter(r=>r.account_id==account);
 if(category!=='all')rows=rows.filter(r=>r.category===category);
 if(direction!=='all')rows=rows.filter(r=>r.type===direction);
 if(['attendance','payrolls'].includes(page))rows=rows.filter(r=>(r.period||r.date.slice(0,7))===month);
 if(from)rows=rows.filter(r=>(r.date||r.next_due||r.joining_date)>=from);
 if(to)rows=rows.filter(r=>(r.date||r.next_due||r.joining_date)<=to);
 const exportRows=()=>exportCSV(page,rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,['total','paid','due','amount','balance','salary','net','earned','credit'].includes(k)?Number(v)/100:v]))));const total=key=>sum(rows,key);
 return <>{page==='cashbook'?<><div className="account-grid">{data.accounts.map(a=><Link className="account-card" href={'/cashbook/'+a.id} key={a.id}><span className="account-card-top"><span className="stat-icon"><Landmark size={20}/></span><ArrowUpRight size={17}/></span><span>{a.name} <small>{a.number}</small></span><strong>{money(a.balance)}</strong><span className="account-card-bottom">{a.type} account <span>View book <ArrowRight size={14}/></span></span></Link>)}</div><div className="notice"><Info size={16}/>Invoices do not change cash balances. Only actual receipts, payments, and authorised entries appear here.{admin&&<button className="text-button" onClick={()=>open('manual-entry')}>Manual entry <Plus size={14}/></button>}</div></>:<div className="module-summary"><Stat label="Total records" value={String(rows.length).padStart(2,'0')} note="Matching your current filters" icon={FileText}/><Stat label={page==='customers'?'Customer outstanding':page==='employees'?'Monthly salary commitments':page==='attendance'?'Present records':page==='gate-passes'?'Outward movements':page==='payrolls'?'Net payroll':page==='invoices'?'Total invoiced':'Total amount'} value={['attendance','gate-passes'].includes(page)?String(rows.filter(r=>r.status==='Present'||r.type==='Outward').length):money(page==='customers'?total('balance'):page==='employees'?sum(rows.filter(e=>e.salary_type==='Monthly'),'salary'):page==='payrolls'?total('net'):page==='invoices'?sum(rows.filter(i=>i.status!=='Voided'),'total'):total('amount'))} note={page==='employees'?'Daily staff paid from attendance':'Calculated from your records'} icon={Wallet}/><Stat label={page==='invoices'?'Awaiting collection':page==='receipts'?'Customer credit':page==='payrolls'?'Remaining payable':'Connected workspace'} value={page==='invoices'?money(total('due')):page==='receipts'?money(total('credit')):page==='payrolls'?money(total('net')-total('paid')):'All in sync'} note="Source records are one click away" icon={Layers}/></div>}
 <div className="module-filters"><div className="filter-left"><SlidersHorizontal size={16}/>{['customers','employees','invoices'].includes(page)&&<select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{(page==='invoices'?['Unpaid','Partially Paid','Paid','Voided']:['Active','Inactive']).map(s=><option key={s}>{s}</option>)}</select>}{['cashbook','expenses','receipts'].includes(page)&&<select aria-label="Filter by account" value={account} onChange={e=>setAccount(e.target.value)}><option value="all">All accounts</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>}{['expenses','fixed-expenses'].includes(page)&&<select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set((data[table]||[]).map(e=>e.category))].map(c=><option key={c}>{c}</option>)}</select>}{page==='cashbook'&&<select aria-label="Transaction direction" value={direction} onChange={e=>setDirection(e.target.value)}><option value="all">All movements</option><option value="in">Money in</option><option value="out">Money out</option></select>}{['attendance','payrolls'].includes(page)?<input type="month" aria-label="Month" value={month} onChange={e=>setMonth(e.target.value)}/>:!['customers','employees'].includes(page)&&<><input type="date" aria-label="From date" value={from} onChange={e=>setFrom(e.target.value)}/><span>to</span><input type="date" aria-label="To date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></>}</div><button className="button secondary small" onClick={exportRows}><Download size={15}/>Export CSV</button></div><Table rows={rows} columns={columns[page]} searchPlaceholder={`Search ${page.replaceAll('-',' ')}…`}/></>;
}
