import React,{useState} from 'react';
import {Link,useForm} from '@inertiajs/react';
import {ArrowUpRight,Download,CalendarDays,Info,ReceiptText,Wallet,Landmark,ChartNoAxesCombined,Layers} from 'lucide-react';
import {Card,Stat,Table,Ref,Empty,Field,money,dateLabel,code,sum,exportCSV} from './UI';
import {useColumns} from './Modules';
export function CustomerLedger({data,customer}) {
 const [from,setFrom]=useState(''),[to,setTo]=useState('');
 const rows=[...data.invoices.filter(i=>i.customer_id===customer.id&&i.status==='Posted').map(i=>({id:'i'+i.id,date:i.date,type:'Invoice',source:'invoices',sourceId:i.id,debit:i.total,credit:0,description:i.notes||'Sale invoice'})),...data.receipts.filter(r=>r.customer_id===customer.id).map(r=>({id:'r'+r.id,date:r.date,type:'Receipt',source:'receipts',sourceId:r.id,debit:0,credit:r.amount,description:r.reference||'Customer payment'}))].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id,undefined,{numeric:true}));
 let balance=Number(customer.opening_balance);const ledger=rows.map(r=>{balance+=Number(r.debit)-Number(r.credit);return {...r,balance}});const filtered=ledger.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));const opening=from?(ledger.filter(r=>r.date<from).at(-1)?.balance??customer.opening_balance):customer.opening_balance;
 return <><div className="module-filters"><div className="filter-left"><input aria-label="Ledger from date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>to</span><input aria-label="Ledger to date" type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/><span>Opening {money(opening)}</span></div><button className="button secondary small" onClick={()=>exportCSV('customer-ledger',filtered.map(r=>({date:r.date,type:r.type,reference:code(r.source,r.sourceId),debit:r.debit/100,credit:r.credit/100,balance:r.balance/100})))}><Download size={15}/>Export</button></div><Table rows={filtered} columns={[{key:'date',label:'Date',render:r=>dateLabel(r.date)},{key:'type',label:'Type'},{key:'ref',label:'Reference',render:r=><Ref type={r.source} id={r.sourceId}/>},{key:'description',label:'Description'},{key:'debit',label:'Debit',right:true,render:r=>r.debit?money(r.debit):'—'},{key:'credit',label:'Credit',right:true,render:r=>r.credit?money(r.credit):'—'},{key:'balance',label:'Running balance',right:true,render:r=><strong>{money(r.balance)}</strong>}]}/><div className="ledger-ending"><span>Closing balance for selected period</span><strong>{money(filtered.at(-1)?.balance??opening)}</strong><span>Current customer balance</span><strong>{money(customer.balance)}</strong></div></>;
}
export function Ledgers({data}){
 const [tab,setTab]=useState('Invoice ledger'),[selected,setSelected]=useState(data.customers[0]?.id||'');const cols=useColumns(data,()=>{},false);const customer=data.customers.find(c=>c.id==selected);
 return <><div className="tabs">{['Invoice ledger','Customer ledger'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Invoice ledger'?<><div className="notice"><Info size={16}/>Click an invoice’s paid amount to view the receipts that make up its balance.</div><Table rows={data.invoices.map(i=>({...i,customer_name:data.customers.find(c=>c.id===i.customer_id)?.name}))} columns={cols.invoices}/></>:<><div className="module-filters"><select aria-label="Select customer ledger" value={selected} onChange={e=>setSelected(e.target.value)}>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name} · {code('customers',c.id)}</option>)}</select>{customer&&<Ref type="customers" id={customer.id}>Open customer profile <ArrowUpRight size={14}/></Ref>}</div>{customer?<CustomerLedger key={customer.id} data={data} customer={customer}/>:<Empty/>}</>}</>;
}
export function Reports({data,today}){
 const params=new URLSearchParams(window.location.search);const [tab,setTab]=useState(params.get('group')||'Profit & loss'),[from,setFrom]=useState(today.slice(0,7)+'-01'),[to,setTo]=useState(today),[employee,setEmployee]=useState(params.get('employee')||'all');
 const selected=rows=>rows.filter(r=>(r.date||r.period+'-01')>=from&&(r.date||r.period+'-01')<=to);
 const invoices=selected(data.invoices).filter(i=>i.status==='Posted');const expenses=selected(data.expenses);const payroll=data.payrolls.filter(p=>p.period>=from.slice(0,7)&&p.period<=to.slice(0,7));const production=(data.production||[]).filter(r=>r.date>=from&&r.date<=to);
 const revenue=sum(invoices,'total'),variable=sum(expenses.filter(e=>!e.fixed_expense_id),'amount'),fixed=sum(expenses.filter(e=>e.fixed_expense_id),'amount'),salary=sum(payroll,'net');
 const pl=[{name:'Sales revenue',amount:revenue,href:'/invoices'},{name:'Variable expenses',amount:-variable,href:'/expenses'},{name:'Fixed expenses paid',amount:-fixed,href:'/expenses'},{name:'Payroll expense',amount:-salary,href:'/payrolls'},{name:'Net profit / loss',amount:revenue-variable-fixed-salary,href:null}];
 const hr=data.employees.filter(e=>employee==='all'||e.id==employee).map(e=>{const attendance=selected(data.attendance).filter(a=>a.employee_id===e.id);const pay=payroll.filter(p=>p.employee_id===e.id);return {...e,present:attendance.filter(a=>a.status==='Present').length,absent:attendance.filter(a=>a.status==='Absent').length,leave:attendance.filter(a=>a.status==='Leave').length,half:attendance.filter(a=>a.status==='Half Day').length,overtime:sum(attendance,'overtime'),gross:sum(pay,'earned')+sum(pay,'allowances')+sum(pay,'overtime_pay'),deductions:sum(pay,'deductions'),net:sum(pay,'net'),paid:sum(pay,'paid')}});
 const cols=useColumns(data,()=>{},false);
 const exportReport=()=>exportCSV(tab,tab==='Profit & loss'?pl.map(r=>({category:r.name,amount:r.amount/100})):tab==='HRMS'?hr.map(r=>({employee:r.name,present:r.present,absent:r.absent,leave:r.leave,half_days:r.half,overtime:r.overtime,gross:r.gross/100,deductions:r.deductions/100,net:r.net/100,paid:r.paid/100})):tab==='Production'?production:invoices.map(r=>({invoice:code('invoices',r.id),customer:data.customers.find(c=>c.id===r.customer_id)?.name,total:r.total/100,paid:r.paid/100,due:r.due/100})));
 return <><div className="tabs">{['Profit & loss','HRMS','Receivables','Production'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="module-filters"><div className="filter-left"><CalendarDays size={16}/><input aria-label="Report from date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>to</span><input aria-label="Report to date" type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/>{tab==='HRMS'&&<select aria-label="Report employee" value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">All employees</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select>}</div><button className="button secondary small" onClick={exportReport} ><Download size={15}/>Export report</button></div>
 {tab==='Profit & loss'&&<><div className="notice"><Info size={16}/>Basis: posted invoice revenue, paid operating expenses, generated payroll for months in range. Cash collections are excluded from revenue to avoid counting sales twice.</div><div className="module-summary"><Stat label="Sales revenue" value={money(revenue)} note={`${invoices.length} posted invoices`} icon={ReceiptText}/><Stat label="Total expenses" value={money(variable+fixed+salary)} note="Operating expenses + earned payroll" icon={Wallet}/><Stat label="Net profit / loss" value={money(revenue-variable-fixed-salary)} note="Revenue less recognised expenses" icon={ChartNoAxesCombined} accent/></div><Card title="Profit & loss statement" subtitle={`${dateLabel(from)} — ${dateLabel(to)}`}><div className="pl-statement">{pl.map(r=><div key={r.name}>{r.href?<Link href={r.href}>{r.name}<ArrowUpRight size={15}/></Link>:<strong>{r.name}</strong>}<strong>{money(r.amount)}</strong></div>)}</div></Card><Card title="Expense category detail" className="section-gap"><Table rows={expenses} columns={cols.expenses}/></Card></>}
 {tab==='HRMS'&&<><div className="notice">Attendance follows exact selected dates. Payroll includes complete monthly records for months in range. {data.employees.filter(e=>e.status==='Active').length} active / {data.employees.filter(e=>e.status!=='Active').length} inactive employees.</div><Table rows={hr} columns={[{key:'name',label:'Employee',render:r=><Ref type="employees" id={r.id}>{r.name}</Ref>},{key:'present',label:'Present'},{key:'absent',label:'Absent'},{key:'leave',label:'Leave'},{key:'half',label:'Half day'},{key:'overtime',label:'OT hours'},{key:'gross',label:'Gross',render:r=>money(r.gross)},{key:'deductions',label:'Deductions',render:r=>money(r.deductions)},{key:'net',label:'Net',render:r=>money(r.net)},{key:'paid',label:'Paid',render:r=>money(r.paid)}]}/><Card title="Payroll records" className="section-gap"><Table rows={payroll.filter(p=>employee==='all'||p.employee_id==employee)} columns={cols.payrolls}/></Card></>}
 {tab==='Receivables'&&<><div className="module-summary"><Stat label="Invoiced in period" value={money(sum(invoices,'total'))} note="Posted invoices" icon={ReceiptText}/><Stat label="Outstanding on these invoices" value={money(sum(invoices,'due'))} note="Current due, after all allocations" icon={Wallet}/><Stat label="Customer advances" value={money(sum(data.receipts,'credit'))} note="All-time unallocated credit" icon={Landmark}/></div><Table rows={invoices} columns={cols.invoices}/></>}
 {tab==='Production'&&<><div className="notice"><Info size={16}/>Production reports read your existing production records from storage/app/production.csv. No production entry records are created here.</div>{production.length?<Table rows={production} columns={[{key:'date',label:'Date',render:r=>dateLabel(r.date)},{key:'reference',label:'Production reference',render:r=>r.source_url?<a className="record-link" href={r.source_url} target="_blank" rel="noreferrer">{r.reference}<ArrowUpRight size={14}/></a>:r.reference},{key:'item',label:'Item'},{key:'quantity',label:'Quantity',right:true,render:r=>new Intl.NumberFormat().format(r.quantity)},{key:'unit',label:'Unit'}]}/>:<Card title="Production report"><Empty title="No production records in this period" text="Add storage/app/production.csv with date, reference, item, quantity, unit, and optional source_url columns to report existing production data."/></Card>}</>}</>;
}
export function AuditTable({rows}){return <Table rows={rows} columns={[{key:'created_at',label:'When',render:r=>new Date(r.created_at).toLocaleString()},{key:'action',label:'Action'},{key:'user_id',label:'User ID'},{key:'entity_id',label:'Record ID'},{key:'details',label:'Details',render:r=><details><summary>View audit details</summary><pre className="audit-json">{JSON.stringify(JSON.parse(r.details||'{}'),null,2)}</pre></details>}]}/>}
export function SettingsPage({user,data,demo}){
 const form=useForm({name:user.name,current_password:'',password:'',password_confirmation:''});
 return <><div className="settings-grid"><Card title="Your profile" subtitle="Update your name and secure your account."><form onSubmit={e=>{e.preventDefault();form.post('/profile',{onSuccess:()=>form.reset('current_password','password','password_confirmation')})}} className="settings-form">{[['name','Full name','text'],['current_password','Current password','password'],['password','New password (12+ characters)','password'],['password_confirmation','Confirm new password','password']].map(([key,label,type])=><Field key={key} label={label} error={form.errors[key]}><input required minLength={key==='password'?12:undefined} type={type} value={form.data[key]} onChange={e=>form.setData(key,e.target.value)} autoComplete={key==='current_password'?'current-password':type==='password'?'new-password':'name'}/></Field>)}<button className="button primary" disabled={form.processing}>Save profile</button></form></Card><Card title="Workspace information" subtitle="A connected foundation for your business."><div className="settings-info"><Layers size={40}/><h2>Threadline</h2><p>Textile management workspace</p><div><span>Environment</span><strong>{demo?'Local demo':'Business workspace'}</strong></div><div><span>Currency</span><strong>USD ($)</strong></div><div><span>Your role</span><strong>{user.role}</strong></div><div><span>Financial records</span><strong>Audited & connected</strong></div><div><span>Salary basis</span><strong>Calendar-day monthly / daily</strong></div></div></Card></div><Card title="Workspace activity & audit trail" subtitle="Every save is recorded with its user, timestamp, and source details." className="section-gap"><AuditTable rows={data.audit_logs}/></Card></>;
}
