import React, {useState,useEffect} from 'react';
import {useForm} from '@inertiajs/react';
import {Plus, Trash2, ArrowRight, Info, Check} from 'lucide-react';
import {Field, Modal, money, code, sum} from './UI';
const titles={'customers':'Add customer','update-customer':'Edit customer','delete-customer':'Delete customer','invoices':'Create invoice','fabric-costings':'Calculate fabric cost','receipts':'Receive money','employees':'Add employee','update-employee':'Edit employee','delete-employee':'Delete employee','attendance':'Mark attendance','payrolls':'Generate payroll','pay-salary':'Pay salary','expenses':'Record expense','fixed-expenses':'New recurring expense','pay-fixed':'Pay recurring expense','defer-fixed':'Defer recurring expense','gate-passes':'Create gate pass','update-gate-pass':'Edit gate pass','delete-gate-pass':'Delete gate pass','accounts':'Add account','manual-entry':'Manual cash entry','void-invoice':'Void invoice'};
export default function TransactionForm({action,data,today,initial={},onClose,onSaved}) {
 const [inline,setInline]=useState(false); const [unitCreator,setUnitCreator]=useState(false); const [accountTypeCreator,setAccountTypeCreator]=useState(false);
 const defaults={submission_key:crypto.randomUUID(),date:today,due_date:today,joining_date:today,next_due:today,
 name:'',phone:'',email:'',address:'',tax_id:'',customer_id:'',account_id:'',employee_id:'',invoice_id:'',
 amount:'',salary:'',description:'',category:'',notes:'',reference:'',method:action==='receipts'?'':'Bank transfer',allocation_mode:'oldest',allocations:[],
 type:action==='accounts'?'Bank':action==='manual-entry'?'out':'Outward',opening_balance:0,salary_type:'Monthly',period:today.slice(0,7),
 allowances:0,deductions:0,overtime_rate:0,overtime:0,status:'Present',employee_ids:[],check_in:'',check_out:'',remarks:'',
 discount:0,frequency:'Monthly',department:'',designation:'',vehicle:'',driver:'',quantity:1,unit:'Meter',purpose:'Customer delivery',authorised_by:'',party:'',reason:'',number:'',
 read:60,pick:40,warp_count:40,weft_count:40,width:44,yarn_warp_rate:0,yarn_weft_rate:0,conversion_rate:0,costing_ids:[],
 items:[{description:'',unit:'Meter',quantity:1,rate:''}],...initial};
 const form=useForm(defaults); const v=form.data; const set=form.setData;
 const customers=data.customers.filter(c=>c.status==='Active'||c.id==v.customer_id);
 const employees=data.employees.filter(e=>e.status==='Active');
 const outstanding=data.invoices.filter(i=>i.customer_id==v.customer_id&&i.due>0);
 const unitMultiplier=name=>Number(data.units?.find(u=>u.name_key===String(name).trim().toLowerCase())?.meters_per_unit||1);
 const total=sum(v.items.map(i=>({amount:Math.round(Number(i.quantity)*unitMultiplier(i.unit)*Math.round(Number(i.rate)*100))})),'amount')-Math.round(Number(v.discount||0)*100);
 const availableCostings=data.fabric_costings?.filter(c=>!c.invoice_id)||[];
 const toggleCosting=(costing,checked)=>{
  const ids=checked?[...v.costing_ids,costing.id]:v.costing_ids.filter(id=>id!==costing.id);
  const description=costing.name||`Fabric costing #${costing.id}`;
  const existing=v.items.findIndex(item=>item.costing_id===costing.id);
  const items=checked?(existing<0?[...v.items.filter(item=>item.description||item.rate),{costing_id:costing.id,description,unit:'Meter',quantity:costing.quantity,rate:(Number(costing.fabric_rate_per_mtr)/100).toFixed(2)}]:v.items):v.items.filter(item=>item.costing_id!==costing.id);
  set({...v,costing_ids:ids,items:items.length?items:[{description:'',unit:'Meter',quantity:1,rate:''}]});
 };
 const customer=data.customers.find(c=>c.id==v.customer_id);
 function input(key,label,type='text',required=true,extra={}) {return <Field key={key} label={label} error={form.errors[key]}><input type={type} required={required} value={v[key]??''} onChange={e=>set(key,e.target.value)} {...(type==='number'?{step:'0.01',min:0}:{} )} {...extra}/></Field>}
 function select(key,label,options,required=true) {return <Field key={key} label={label} error={form.errors[key]}><select required={required} value={v[key]??''} onChange={e=>set(key,e.target.value)}><option value="">Select {label.toLowerCase()}</option>{options.map(o=><option key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</option>)}</select></Field>}
 const accounts=()=>select('account_id',action==='receipts'?'Received into':'Pay from',data.accounts.map(a=>({value:a.id,label:a.name+' \u00b7 '+money(a.balance)})));
 const employee=()=>select('employee_id','Employee',employees.map(e=>({value:e.id,label:e.name+' \u00b7 '+code('employees',e.id)})));
 const customerSelect=()=> <div className="wide customer-picker"><Field label="Customer" error={form.errors.customer_id}><input list="customer-lookup" placeholder="Search name, code, or phone\u2026" value={v.customer_search??(customer?customer.name:'')} onChange={e=>{const text=e.target.value;const found=data.customers.find(c=>[c.name,c.phone,code('customers',c.id),`${c.name} ? ${c.phone}`].some(x=>x?.toLowerCase()===text.toLowerCase()));set({...v,customer_search:text,customer_id:found?.id||'',allocations:[]})}}/><datalist id="customer-lookup">{customers.map(c=><option key={c.id} value={`${c.name} ? ${c.phone}`}>{code('customers',c.id)}</option>)}</datalist></Field><button type="button" className="text-button" onClick={()=>setInline(true)}><Plus size={14}/>New customer</button>{customer&&<div className="inline-note"><Check size={15}/>{customer.phone} <span>Outstanding: {money(customer.balance)}</span></div>}</div>;
 const receiptAccount=data.accounts.find(a=>a.id==v.account_id);
 const paymentMethods=account=>{
  if(!account)return [];
  const type=String(account.type||'').trim();
  if(type.toLowerCase()==='cash')return ['Cash'];
  if(type.toLowerCase()==='bank')return ['Bank transfer','Cheque','Card','Other'];
  return [...new Set([type||account.name,'Online','Other'])];
 };
 const methodOptions=paymentMethods(receiptAccount);
 const defaultPaymentMethod=account=>account?.type?.toLowerCase()==='cash'?'Cash':account?.type?.toLowerCase()==='bank'?'Bank transfer':account?.type||account?.name||'';
 useEffect(()=>{if(action==='receipts'&&receiptAccount&&!v.method)set('method',defaultPaymentMethod(receiptAccount))},[action,v.account_id]);
 const receivedInto=()=> <Field label="Received into" error={form.errors.account_id}><select required value={v.account_id} onChange={e=>{const account=data.accounts.find(a=>a.id==e.target.value);set({...v,account_id:e.target.value,method:defaultPaymentMethod(account)})}}><option value="">Select account</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.balance)}</option>)}</select></Field>;
 function submit(e){e.preventDefault();form.post('/actions/'+action,{preserveScroll:true,onSuccess:page=>{onSaved?.(page);onClose()}})}
 const itemChange=(index,key,val)=>set('items',v.items.map((item,i)=>i===index?{...item,[key]:val}:item));
 if(['delete-gate-pass','delete-employee','delete-customer'].includes(action)) {const employeeRecord=action==='delete-employee';const customerRecord=action==='delete-customer';const label=employeeRecord?'employee':customerRecord?'customer':'gate pass';const protectedHistory=(employeeRecord||customerRecord)&&v.has_history;const historyText=employeeRecord?'payroll or attendance':'invoice or receipt';return <Modal title={`Delete ${label}`} onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="notice wide">{protectedHistory?<> <strong>{v.name}</strong> has {historyText} history and cannot be deleted. Deactivate the {label} instead.</>:<>Delete <strong>{v.name}</strong>? This removes the {label} from active records. The action will be recorded in the audit log.</>}</div>{form.errors.id&&<p className="field-error">{form.errors.id}</p>}</div><div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button>{!protectedHistory&&<button className="button danger" disabled={form.processing}>{form.processing?'Deleting…':`Delete ${label}`}</button>}</div></form></Modal>}
 return <><Modal title={titles[action]||'New record'} onClose={onClose} wide={['invoices','receipts','attendance','update-gate-pass'].includes(action)}><form onSubmit={submit}><div className="modal-body"><div className="form-grid">
 {['customers','update-customer'].includes(action)&&<>{input('name','Customer / business name')}{input('phone','Phone number','tel')}{input('email','Email address','email',false)}{input('tax_id','Tax / business ID','text',false)}{input('address','Address','text',false)}{input('opening_balance','Opening balance ($)','number',false,{step:'0.01'})}{action==='update-customer'&&select('status','Customer status',['Active','Inactive'])}{data.customers.filter(c=>c.id!==v.id&&c.phone.replace(/\D/g,'')===v.phone.replace(/\D/g,'')&&v.phone).map(c=><div key={c.id} className="notice wide">This number belongs to {c.name}. <a href={'/customers/'+c.id}>Use existing customer \u2192</a></div>)}</>}
 {action==='invoices'&&<>{customerSelect()}{input('date','Invoice date','date')}{input('due_date','Due date','date')}<div className="wide line-items"><div className="section-label">Invoice items <button type="button" className="text-button" onClick={()=>setUnitCreator(true)}><Plus size={14}/>Add unit</button> <span>Quantity × rate</span></div>{v.items.map((item,i)=><div className="line-item" key={i}><input aria-label={`Item ${i+1} description`} placeholder="Fabric / item description" required value={item.description} onChange={e=>itemChange(i,'description',e.target.value)}/><input aria-label={`Item ${i+1} unit`} list="units" value={item.unit} required onChange={e=>itemChange(i,'unit',e.target.value)}/><input aria-label={`Item ${i+1} quantity`} type="number" step="0.001" min="0.001" placeholder="Qty" required value={item.quantity} onChange={e=>itemChange(i,'quantity',e.target.value)}/><input aria-label={`Item ${i+1} rate`} type="number" step="0.01" min="0.01" placeholder="Rate" required value={item.rate} onChange={e=>itemChange(i,'rate',e.target.value)}/><strong>{money(Math.round(Number(item.quantity)*unitMultiplier(item.unit)*Math.round(Number(item.rate)*100)))}</strong><button type="button" className="icon-button" disabled={v.items.length===1} onClick={()=>set('items',v.items.filter((_,j)=>j!==i))} aria-label="Remove item"><Trash2 size={15}/></button></div>)}<button type="button" className="text-button" onClick={()=>set('items',[...v.items,{description:'',unit:'Meter',quantity:1,rate:''}])}><Plus size={15}/>Add another item</button></div>{availableCostings.length>0&&<div className="wide allocation-grid"><div className="section-label">Link saved costing <span>Optional · selecting one adds its rate and quantity as an invoice item</span></div>{availableCostings.map(c=><label className="checkbox" key={c.id}><input type="checkbox" checked={v.costing_ids.includes(c.id)} onChange={e=>toggleCosting(c,e.target.checked)}/>{c.name||`Costing #${c.id}`} · {Number(c.quantity)} m · {money(c.fabric_rate_per_mtr)}/m</label>)}</div>}{input('discount','Invoice discount ($)','number',false)}{input('notes','Reference / notes','text',false)}<div className="form-total wide"><span>Invoice total</span><strong>{money(total)}</strong></div><div className="notice wide"><Info size={16}/>This creates a receivable. Record payment separately in Receive Money.</div></>}
 {action==='fabric-costings'&&<>{input('name','Costing name','text',false)}{input('quantity','Quantity (m)','number')}{input('read','Read / EPI','number')}{input('pick','Pick / PPI','number')}{input('warp_count','Warp count (Ne)','number')}{input('weft_count','Weft count (Ne)','number')}{input('width','Width (inches)','number')}{input('yarn_warp_rate','Warp yarn rate / kg ($)','number')}{input('yarn_weft_rate','Weft yarn rate / kg ($)','number')}{input('conversion_rate','Conversion rate ($ per pick)','number')}<div className="notice wide">Calculates yarn weight, GSM, bag requirements, fabric rate per metre, contract value, and 17% estimated sales tax. Saved calculations can be linked to an invoice.</div></>}
 {action==='receipts'&&<>{customerSelect()}{input('date','Receipt date','date')}{input('amount','Amount received ($)','number')}{receivedInto()}{select('method','Payment method',methodOptions.length?methodOptions:['Select an account first'])}{input('reference','Transaction reference','text',false)}{select('allocation_mode','Allocate payment',['oldest','manual'])}<div className="wide allocation-grid"><div className="section-label">Outstanding invoices <span>{outstanding.length} available</span></div>{!outstanding.length&&<p className="muted-text">Any payment will remain as customer credit.</p>}{outstanding.map(i=><div className="allocation-row" key={i.id}><div><strong>{code('invoices',i.id)}</strong><small>{i.date}</small></div><span>Due {money(i.due)}</span>{v.allocation_mode==='manual'?<input type="number" min="0" max={i.due/100} step="0.01" aria-label={'Allocate '+code('invoices',i.id)} placeholder="0.00" value={v.allocations.find(a=>a.invoice_id===i.id)?.amount??''} onChange={e=>set('allocations',[...v.allocations.filter(a=>a.invoice_id!==i.id),{invoice_id:i.id,amount:e.target.value||0}])}/>:<span className="badge">Oldest first</span>}</div>)}</div><div className="notice wide"><Info size={16}/>Any excess remains as customer credit. Your receipt and cash book update together.</div></>}
 {['employees','update-employee'].includes(action)&&<>{input('name','Full name')}{input('phone','Phone number','tel')}{input('department','Department')}{input('designation','Designation')}{input('joining_date','Joining date','date')}{select('salary_type','Salary basis',['Monthly','Daily'])}{input('salary','Base salary / daily rate ($)','number')}{action==='update-employee'&&select('status','Employment status',['Active','Inactive'])}{action==='employees'&&<div className="notice wide">After saving, record attendance and use the payroll shortcut in this employee’s row. Payroll is calculated from attendance for the selected month.</div>}</>}
 {action==='attendance'&&<>{input('date','Attendance date','date')}{select('status','Status',['Present','Absent','Leave','Half Day','Off'])}<div className="wide"><div className="section-label">Employees <button type="button" className="text-button" onClick={()=>set('employee_ids',v.employee_ids.length===employees.length?[]:employees.map(e=>e.id))}>Select all / clear</button></div><div className="employee-checks">{employees.map(e=><label className="checkbox" key={e.id}><input type="checkbox" checked={v.employee_ids.includes(e.id)} onChange={ev=>set('employee_ids',ev.target.checked?[...v.employee_ids,e.id]:v.employee_ids.filter(id=>id!==e.id))}/>{e.name}</label>)}</div></div>{input('check_in','Check-in','time',false)}{input('check_out','Check-out','time',false)}{input('overtime','Overtime hours','number',false)}{input('remarks','Remarks','text',false)}</>}
 {action==='payrolls'&&<>{employee()}{input('period','Payroll month','month')}{input('allowances','Allowances ($)','number',false)}{input('deductions','Other deductions ($)','number',false)}{input('overtime_rate','Overtime hourly rate ($)','number',false)}<div className="notice wide">Monthly: base \u00f7 calendar days, less recorded absences and half days. Leave/off are paid; unmarked days are assumed paid. Daily: present + \u00bd half days. Attendance overtime \u00d7 hourly rate. Re-generating updates only unpaid payroll.</div></>}
 {action==='pay-salary'&&<>{select('payroll_id','Payroll record',data.payrolls.filter(p=>p.net>p.paid).map(p=>({value:p.id,label:`${data.employees.find(e=>e.id===p.employee_id)?.name} ? ${p.period} \u00b7 Due ${money(p.net-p.paid)}`})))}{input('date','Payment date','date')}{accounts()}{input('amount','Payment amount ($)','number')}</>}
 {['expenses','pay-fixed'].includes(action)&&<>{input('date','Payment date','date')}{input('amount','Amount ($)','number')}{accounts()}{action==='expenses'&&<>{input('category','Category')}{input('description','Description')}</>}{input('party','Party / payee','text',false)}{input('reference','Voucher / document reference','text',false)}</>}
 {action==='fixed-expenses'&&<>{input('name','Expense name')}{input('category','Category')}{input('amount','Expected amount ($)','number')}{input('next_due','Next due date','date')}{select('frequency','Frequency',['Monthly','Quarterly','Yearly'])}{accounts()}</>}
 {action==='defer-fixed'&&<>{input('next_due','Defer until','date')}{input('reason','Reason for deferring')}</>}
 {['gate-passes','update-gate-pass'].includes(action)&&<>{input('name','Gate pass name')}{input('date','Movement date','date')}{select('type','Movement type',['Outward','Inward'])}<Field label="Linked invoice (optional)" error={form.errors.invoice_id}><select value={v.invoice_id} onChange={e=>{const inv=data.invoices.find(i=>i.id==e.target.value);const items=data.invoice_items.filter(i=>i.invoice_id===inv?.id);set({...v,invoice_id:e.target.value,customer_id:inv?.customer_id||'',description:items.map(i=>i.description).join(', '),quantity:items.length===1?items[0].quantity:1,unit:items.length===1?items[0].unit:'Lot'})}}><option value="">No linked invoice</option>{data.invoices.filter(i=>i.status==='Posted').map(i=><option key={i.id} value={i.id}>{code('invoices',i.id)} \u00b7 {data.customers.find(c=>c.id===i.customer_id)?.name}</option>)}</select></Field>{select('customer_id','Customer (optional)',customers.map(c=>({value:c.id,label:c.name})),false)}{input('party','Other party','text',false)}{input('vehicle','Vehicle number','text',false)}{input('driver','Driver','text',false)}{input('description','Goods / material description')}{input('quantity','Quantity','number',true,{step:'0.001'})}{input('unit','Unit','text',true,{list:'units'})}{input('purpose','Purpose / remarks')}{input('authorised_by','Authorised by')}</>}
 {action==='accounts'&&<>{input('name','Account name')}<div className="account-type-control">{select('type','Account type',['Cash','Bank',...(data.account_types||[]).map(t=>t.name)])}<button type="button" className="icon-button account-type-add" aria-label="Create account type" title="Create account type" onClick={()=>setAccountTypeCreator(true)}><Plus size={16}/></button></div>{input('number','Masked account number','text',false)}{input('opening_balance','Opening balance ($)','number')}</>}
 {action==='manual-entry'&&<>{accounts()}{input('date','Transaction date','date')}{select('type','Direction',[{value:'in',label:'Money in'},{value:'out',label:'Money out'}])}{input('amount','Amount ($)','number')}{input('description','Reason for entry')}</>}
 {action==='void-invoice'&&<><div className="notice wide">The invoice stays in audit history. Any allocated payments become customer credit; cash receipts remain unchanged.</div>{input('reason','Reason for cancellation')}</>}
 </div>{Object.keys(form.errors).length>0&&<div className="form-errors" role="alert">{Object.entries(form.errors).map(([k,e])=><p key={k}>{e}</p>)}</div>}<datalist id="units">{[...new Set(['Piece','Meter','Yard','Kg','Dozen','Bundle','Roll','Lot',...(data.units||[]).map(u=>u.name)])].map(u=><option key={u} value={u}/>)}</datalist></div><div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={form.processing}>{form.processing?'Saving…':action==='receipts'?'Post receipt':action==='invoices'?'Create invoice':['update-gate-pass','update-employee','update-customer'].includes(action)?'Save changes':'Save record'}<ArrowRight size={16}/></button></div></form></Modal>{accountTypeCreator&&<AccountTypeCreator onClose={()=>setAccountTypeCreator(false)} onCreated={type=>{set('type',type.name);setAccountTypeCreator(false)}}/>}{unitCreator&&<UnitCreator onClose={()=>setUnitCreator(false)} onCreated={()=>setUnitCreator(false)}/>} {inline&&<TransactionForm action="customers" data={data} today={today} onClose={()=>setInline(false)} onSaved={page=>{const c=page.props.data.customers[0];set({...v,customer_id:c.id,customer_search:c.name})}}/>}</>;
}

function AccountTypeCreator({onClose,onCreated}) {
 const form=useForm({submission_key:crypto.randomUUID(),name:''});
 const submit=e=>{e.preventDefault();form.post('/actions/account-types',{preserveScroll:true,onSuccess:page=>onCreated(page.props.data.account_types[0])})};

 return <Modal title="Add account type" onClose={onClose}><form onSubmit={submit}><div className="modal-body"><Field label="Account type name" error={form.errors.name}><input autoFocus required maxLength={60} placeholder="e.g. Savings" value={form.data.name} onChange={e=>form.setData('name',e.target.value)}/></Field>{Object.keys(form.errors).length>0&&<div className="form-errors" role="alert">{Object.entries(form.errors).map(([key,error])=><p key={key}>{error}</p>)}</div>}</div><div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={form.processing}>{form.processing?'Saving…':'Save type'}<ArrowRight size={16}/></button></div></form></Modal>;
}

function UnitCreator({onClose,onCreated}) {
 const form=useForm({submission_key:crypto.randomUUID(),name:'',meters_per_unit:''});
 const submit=e=>{e.preventDefault();form.post('/actions/units',{preserveScroll:true,onSuccess:()=>onCreated()})};

 return <Modal title="Add a reusable length unit" onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="form-grid">
  <Field label="Unit name" error={form.errors.name}><input autoFocus required maxLength={30} placeholder="e.g. Guize" value={form.data.name} onChange={e=>form.setData('name',e.target.value)}/></Field>
  <Field label="How many meters in one unit?" error={form.errors.meters_per_unit}><input type="number" required min="0.000001" max="1000000" step="any" placeholder="e.g. 4.5" value={form.data.meters_per_unit} onChange={e=>form.setData('meters_per_unit',e.target.value)}/></Field>
  <div className="notice wide">Saved units stay available in future invoices. Invoice rates for these custom units are entered per meter.</div>
  {Object.keys(form.errors).length>0&&<div className="form-errors wide" role="alert">{Object.entries(form.errors).map(([key,error])=><p key={key}>{error}</p>)}</div>}
 </div></div><div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={form.processing}>{form.processing?'Saving…':'Save unit'}<ArrowRight size={16}/></button></div></form></Modal>;
}
